function sensors = display_sensor(index, n_sensors)
%Receive B matrix's estimate column and return the corresponding sensor
%reading
if n_sensors == 8
    % Get reading of all sensors
    signalreadout = dec2bin(0:2^8-1)-'0';
    signalreadout = signalreadout(index, :);
    % Get positions where row is 1 (sensors that detected obstacles)
    sensors = find(signalreadout==1);   
elseif n_sensors == 4
    % Get reading of all sensors
    signalreadout = [1, 0, 0, 0; ...
        0, 1, 0, 0; ...
        0, 0, 1, 0; ...
        0, 0, 0, 1; ...
        1, 1, 0, 0; ...
        1, 0, 1, 0; ...
        1, 0, 0, 1; ...
        0, 1, 1, 0; ...
        0, 1, 0, 1; ...
        0, 0, 1, 1; ...
        1, 1, 1, 0; ...
        1, 1, 0, 1; ...
        1, 0, 1, 1; ...
        0, 1, 1, 1; ...
        1,1,1,1; ...
        0,0,0,0]
    signalreadout = signalreadout(index, :);
    % Get positions where row is 1 (sensors that detected obstacles)
    sensors = find(signalreadout==1);   
end
% Replace numberf for their sensor meaning
t = ["N", "S", "W", "E", "NW", "NE", "SW", "SE"];
v = [1, 2, 3, 4, 5, 6, 7, 8];
B = string(categorical(sensors,v,t));
disp("Sensors: "); disp(B);
end

